---
- name: Setup Web Server
  hosts: all
  #remote_user: root

  tasks:
    - name: Install Apache Server
      apt:
        name: apache2

    - name: Install PHP
      apt:
        name: php

    - name: Delete content & directory
      file:
        state: absent
        path: '/var/www/html/'

    - name: Set timezone to Africa/Lagos
      community.general.timezone:
        name: Africa/Lagos

    - name: Copy index.php file
      copy:
        src: /home/vagrant/ansible/index.php
        dest: /var/www/html/
